# Generated by Django 6.0.6 on 2026-06-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('hn', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('first_name', models.CharField(db_index=True, max_length=100)),
                ('last_name', models.CharField(db_index=True, max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('line_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'ชาย'), ('F', 'หญิง'), ('O', 'อื่นๆ')], max_length=10, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('subdistrict', models.CharField(blank=True, max_length=100, null=True)),
                ('postcode', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(db_index=True, default='pending', max_length=50)),
                ('chief_complaint', models.TextField(blank=True, null=True)),
                ('present_illness', models.TextField(blank=True, null=True)),
                ('past_history', models.TextField(blank=True, null=True)),
                ('drug_allergy', models.TextField(blank=True, null=True)),
                ('current_medications', models.TextField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'คนไข้',
                'verbose_name_plural': 'คนไข้ทั้งหมด',
                'db_table': 'patients',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['first_name', 'last_name'], name='patients_first_n_a3acf4_idx'), models.Index(fields=['phone'], name='patients_phone_ef6690_idx'), models.Index(fields=['status'], name='patients_status_7c14f6_idx')],
            },
        ),
    ]
