# Generated by Django 6.0.6 on 2026-06-26 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_hn_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='hn',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
