# Generated by Django 6.0.6 on 2026-06-27 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_hn'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor_id', models.CharField(max_length=100)),
                ('target_id', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=200)),
                ('layer', models.CharField(max_length=10)),
                ('client_ip', models.CharField(blank=True, max_length=100, null=True)),
                ('governance_status', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'patient_audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='case_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='genomics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='patient',
            name='id_card',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='labs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='patient',
            name='microbiome',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='patient',
            name='proteomics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hn',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='legacy_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='postcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='PatientBiologicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('axis_1', models.IntegerField(default=50)),
                ('axis_2', models.IntegerField(default=50)),
                ('axis_3', models.IntegerField(default=50)),
                ('axis_4', models.IntegerField(default=50)),
                ('axis_5', models.IntegerField(default=50)),
                ('axis_6', models.IntegerField(default=50)),
                ('axis_7', models.IntegerField(default=50)),
                ('axis_8', models.IntegerField(default=50)),
                ('axis_9', models.IntegerField(default=50)),
                ('axis_10', models.IntegerField(default=50)),
                ('axis_11', models.IntegerField(default=50)),
                ('axis_12', models.IntegerField(default=50)),
                ('axis_13', models.IntegerField(default=50)),
                ('axis_14', models.IntegerField(default=50)),
                ('axis_15', models.IntegerField(default=50)),
                ('axis_16', models.IntegerField(default=50)),
                ('axis_17', models.IntegerField(default=50)),
                ('axis_18', models.IntegerField(default=50)),
                ('axis_19', models.IntegerField(default=50)),
                ('axis_20', models.IntegerField(default=50)),
                ('axis_21', models.IntegerField(default=50)),
                ('axis_22', models.IntegerField(default=50)),
                ('axis_23', models.IntegerField(default=50)),
                ('axis_24', models.IntegerField(default=50)),
                ('axis_25', models.IntegerField(default=50)),
                ('axis_26', models.IntegerField(default=50)),
                ('axis_27', models.IntegerField(default=50)),
                ('axis_28', models.IntegerField(default=50)),
                ('axis_29', models.IntegerField(default=50)),
                ('axis_30', models.IntegerField(default=50)),
                ('axis_31', models.IntegerField(default=50)),
                ('axis_32', models.IntegerField(default=50)),
                ('axis_33', models.IntegerField(default=50)),
                ('axis_34', models.IntegerField(default=50)),
                ('axis_35', models.IntegerField(default=50)),
                ('axis_36', models.IntegerField(default=50)),
                ('axis_37', models.IntegerField(default=50)),
                ('axis_38', models.IntegerField(default=50)),
                ('axis_39', models.IntegerField(default=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='axes_records', to='patients.patient')),
            ],
            options={
                'db_table': 'patient_biological_records',
                'ordering': ['-record_date'],
            },
        ),
    ]
