# Generated by Django 6.0.6 on 2026-06-27 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auditlog_patient_case_summary_patient_genomics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('source', models.CharField(max_length=200)),
                ('axis', models.CharField(default='General', max_length=100)),
                ('type', models.CharField(default='clinical_guideline', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clinical_knowledge',
                'ordering': ['-created_at'],
            },
        ),
    ]
