# Generated by Django 6.0.6 on 2026-06-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_clinicalknowledge'),
    ]

    operations = [
        migrations.CreateModel(
            name='TspiSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_key', models.CharField(max_length=100, unique=True)),
                ('setting_value', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'การตั้งค่าระบบ',
                'verbose_name_plural': 'การตั้งค่าระบบทั้งหมด',
                'db_table': 'tspi_settings',
                'managed': False,
            },
        ),
    ]
