# Generated by Django 6.0.6 on 2026-06-27 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_tspisettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.TextField(db_column='appID')),
                ('userid', models.TextField(db_column='userID')),
                ('branchid', models.TextField(db_column='branchID')),
                ('doctorid', models.TextField(db_column='doctorID')),
                ('date_meet', models.DateField()),
                ('time_meet', models.TextField()),
                ('time_id', models.IntegerField()),
                ('date_at', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
                ('symptom', models.TextField()),
                ('noti_1', models.TextField()),
                ('noti_7', models.TextField()),
                ('noti_now', models.TextField()),
            ],
            options={
                'db_table': 'appointment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LineChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_user_id', models.CharField(db_index=True, max_length=150)),
                ('role', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'line_chats',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LineLinkingToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('line_user_id', models.CharField(db_index=True, max_length=150)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'line_linking_tokens',
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='intake_status',
            field=models.CharField(db_index=True, default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='line_display_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='line_picture_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='line_user_id',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_items', to='patients.patient')),
            ],
            options={
                'db_table': 'patient_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
