# Generated by Django 6.0.6 on 2026-06-27 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_appointment_linechat_linelinkingtoken_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PdpaConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_version', models.CharField(default='v1.0', max_length=10)),
                ('consent_treatment', models.BooleanField(default=False)),
                ('consent_marketing', models.BooleanField(default=False)),
                ('consent_research', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdpa_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pdpa_consents',
                'ordering': ['-signed_at'],
            },
        ),
    ]
