# Generated by Django 6.0.6 on 2026-06-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_pdpaconsent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('FOLLOW_UP', 'ติดตามอาการตรวจหลังเข้าบำบัด'), ('PRE_VISIT_REMINDER', 'แจ้งเตือนนัดหมายล่วงหน้า'), ('NO_SHOW_CHECK', 'ตรวจสอบและแจ้งเตือนเมื่อเบี้ยวตรวจ (No-show)')], db_index=True, default='FOLLOW_UP', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'รอดำเนินการ'), ('processing', 'กำลังดำเนินการ'), ('completed', 'เสร็จสมบูรณ์'), ('failed', 'ล้มเหลว')], db_index=True, default='pending', max_length=20)),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_hn', models.CharField(blank=True, max_length=50, null=True)),
                ('scheduled_for', models.DateTimeField()),
                ('logs', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'automation_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabRangeReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biomarker_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('min_normal', models.FloatField(default=0.0)),
                ('max_normal', models.FloatField(default=0.0)),
                ('min_warning', models.FloatField(default=0.0)),
                ('max_warning', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lab_range_references',
            },
        ),
    ]
