# Generated by Django 6.0.6 on 2026-06-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_automationtask_labrangereference'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalKnowledgeSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField()),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
                ('axis_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'clinical_knowledge_segments',
            },
        ),
    ]
