# Generated by Django 6.0.6 on 2026-06-30 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_clinicalknowledgesegment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TSPIBrainTrainingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('inputs', models.JSONField(blank=True, default=dict)),
                ('output_axes', models.JSONField(blank=True, default=dict)),
                ('output_text', models.TextField(blank=True, null=True)),
                ('engine_used', models.CharField(db_index=True, default='gemini', max_length=50)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brain_training_logs', to='patients.patient')),
            ],
            options={
                'db_table': 'tspi_brain_training_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
