# Generated by Django 6.0.6 on 2026-07-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_tspibraintraininglog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientbiologicalrecord',
            name='axis_1',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientbiologicalrecord',
            name='axis_10',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientbiologicalrecord',
            name='axis_11',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientbiologicalrecord',
            name='axis_12',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientbiologicalrecord',
            name='axis_13',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientbiologicalrecord',
            name='axis_14',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientbiologicalrecord',
            name='axis_15',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientbiologicalrecord',
            name='axis_16',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientbiologicalrecord',
            name='axis_17',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientbiologicalrecord',
            name='axis_18',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientbiologicalrecord',
            name='axis_19',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientbiologicalrecord',
            name='axis_2',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientbiologicalrecord',
            name='axis_20',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientbiologicalrecord',
            name='axis_21',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientbiologicalrecord',
            name='axis_22',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientbiologicalrecord',
            name='axis_23',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientbiologicalrecord',
            name='axis_24',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientbiologicalrecord',
            name='axis_25',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientbiologicalrecord',
            name='axis_26',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientbiologicalrecord',
            name='axis_27',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientbiologicalrecord',
            name='axis_28',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientbiologicalrecord',
            name='axis_29',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientbiologicalrecord',
            name='axis_3',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientbiologicalrecord',
            name='axis_30',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientbiologicalrecord',
            name='axis_31',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientbiologicalrecord',
            name='axis_32',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientbiologicalrecord',
            name='axis_33',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientbiologicalrecord',
            name='axis_34',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientbiologicalrecord',
            name='axis_35',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientbiologicalrecord',
            name='axis_36',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientbiologicalrecord',
            name='axis_37',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientbiologicalrecord',
            name='axis_38',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientbiologicalrecord',
            name='axis_39',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientbiologicalrecord',
            name='axis_4',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientbiologicalrecord',
            name='axis_5',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientbiologicalrecord',
            name='axis_6',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientbiologicalrecord',
            name='axis_7',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientbiologicalrecord',
            name='axis_8',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientbiologicalrecord',
            name='axis_9',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
