# Generated by Django 6.0.6 on 2026-08-21 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_alter_patientbiologicalrecord_axis_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('framework_version', models.CharField(default='39-axis-master-260715', max_length=50)),
                ('inputs_hash', models.CharField(db_index=True, max_length=64)),
                ('ledger', models.JSONField(default=dict)),
                ('is_valid', models.BooleanField(default=True)),
                ('invariant_violations', models.JSONField(blank=True, default=list)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_records', to='patients.patient')),
                ('source_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_records', to='patients.patientbiologicalrecord')),
            ],
            options={
                'db_table': 'patient_analysis_records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'inputs_hash'], name='patient_ana_patient_b2fa10_idx')],
            },
        ),
    ]
