# Generated by Django 6.0.6 on 2026-08-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_analysisrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='tspibraintraininglog',
            name='reviewed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='tspibraintraininglog',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tspibraintraininglog',
            name='reviewed_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
