# Generated by Django 6.0.6 on 2026-08-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_brain_log_reviewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleRegistryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=150, null=True)),
                ('primary_function', models.TextField(blank=True, null=True)),
                ('mechanisms', models.JSONField(blank=True, default=list)),
                ('primary_axes', models.JSONField(blank=True, default=list)),
                ('primary_networks', models.JSONField(blank=True, default=list)),
                ('clinical_indications', models.JSONField(blank=True, default=list)),
                ('contraindications', models.JSONField(blank=True, default=list)),
                ('synergy_with', models.JSONField(blank=True, default=list)),
                ('antagonism_with', models.JSONField(blank=True, default=list)),
                ('mapping_status', models.CharField(choices=[('PROVISIONAL', 'Provisional'), ('APPROVED', 'Approved')], db_index=True, default='PROVISIONAL', max_length=20)),
                ('approved_by', models.CharField(blank=True, max_length=150, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('source_version', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TSPI Module Registry Entry',
                'verbose_name_plural': 'TSPI Module Registry Entries',
                'db_table': 'tspi_module_registry',
                'ordering': ['code'],
            },
        ),
    ]
